import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared-components/Navbar";

const geist = Geist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={geist.variable}>
      <body className="relative not-last:antialiased bg-black">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
