import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared-components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"], // sesuaikan dengan kebutuhan
  display: "swap",
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="relative not-last:antialiased bg-black font-sans">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
