import { Epilogue } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

const epilogue = Epilogue({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-epilogue",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={epilogue.variable}>
      <body className="relative not-last:antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
